version: '3'

services:
    web_server:
        build: web_server
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./web_server/nginx.conf:/etc/nginx/nginx.conf
        links:
          - api


    api:
        build: api
        volumes:
          - ./api/src:/meep/api/src
        expose:
          - 8000
        ports:
          - 8000:8000
        depends_on:
          - db
        environment:
          - DEV_DATABASE_URL=postgresql://meep:supersafe@db:5432/meep_api
        links:
          - db


    db:
        image: postgres:11.3
        environment:
          - POSTGRES_USER=meep
          - POSTGRES_PASSWORD=supersafe
          - POSTGRES_DB=meep_api
        volumes:
          - "postgres_data:/var/lib/postgresql/data"

volumes:
    postgres_data:
